// Mocks generated by Mockito 5.4.4 from annotations
// in pinapp_challenge/test/features/home/domain/usecases/get_post_comments_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pinapp_challenge/core/modules/data_state.dart' as _i2;
import 'package:pinapp_challenge/features/home/domain/models/comment.dart'
    as _i6;
import 'package:pinapp_challenge/features/home/domain/models/post.dart' as _i5;
import 'package:pinapp_challenge/features/home/domain/repositories/i_posts_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostsRepository extends _i1.Mock implements _i3.IPostsRepository {
  MockIPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.Post>>> getAllPosts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPosts,
          [],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.Post>>>.value(
            _FakeDataState_0<List<_i5.Post>>(
          this,
          Invocation.method(
            #getAllPosts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.Post>>>);

  @override
  _i4.Future<_i2.DataState<List<_i6.Comment>>> getPostComments(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostComments,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i6.Comment>>>.value(
            _FakeDataState_0<List<_i6.Comment>>(
          this,
          Invocation.method(
            #getPostComments,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i6.Comment>>>);
}
